//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pizza
{
    using System;
    using System.Collections.Generic;
    
    public partial class cards
    {
        public int id { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string phone { get; set; }
        public Nullable<System.DateTime> lastAction { get; set; }
        public Nullable<int> bonus { get; set; }
        public Nullable<int> rank { get; set; }
    }
}
